CREATE TABLE STUDENT(
    std_id number  generated by default as identity start with 1 increment by 1 primary key,
    std_name varchar(20),
    phy int,
    chem int,
    mat int,
    status varchar(20) generated always as(
    case
        when phy>=12 and chem>=12 and mat>=25 then 'PASS'
        ELSE 'FAIL'
    end
    )VIRTUAL,
        total int generated always as(phy + chem + mat )virtual,
    constraint phy_check check (phy >=0 and phy < =25),
    constraint chem_check check ( chem >=0 and chem <=25),
    constraint mat_check check ( mat >=0 and mat <=50));
    
describe STUDENT;

INSERT INTO STUDENT (std_name, phy, chem, mat) VALUES ('John
Doe', 20, 15, 40);

INSERT INTO STUDENT (std_name, phy, chem, mat) VALUES ('Jane
Smith', 25, 20, 45);

INSERT INTO STUDENT (std_name, phy, chem, mat) VALUES ('Alice
Johnson', 18, 10, 35);


INSERT INTO STUDENT (std_name, phy, chem, mat) VALUES ('Bob
Brown', 22, 25, 50);

INSERT INTO STUDENT (std_name, phy, chem, mat) VALUES ('Charlie
White', 0, 5, 30);

INSERT INTO STUDENT (std_name, phy, chem, mat) VALUES ('David
Wilson', 10, 10, 25);

INSERT INTO STUDENT (std_name, phy, chem, mat) VALUES ('Eva
Black', 15, 12, 38);

INSERT INTO STUDENT (std_name, phy, chem, mat) VALUES ('Frank
Green', 23, 18, 42);

INSERT INTO STUDENT (std_name, phy, chem, mat) VALUES ('Grace
Lee', 14, 8, 22);

INSERT INTO STUDENT (std_name, phy, chem, mat) VALUES ('Henry
King', 25, 15, 47);



select * from STUDENT;


select avg(phy) from STUDENT;
select max(mat) as highest_marks_maths from STUDENT;
select min(chem) as lowest_marks_chem from STUDENT;
select count(std_id) from student where phy>=12;
select std_name from STUDENT  where status = 'PASS';
select std_id,std_name,total,status from STUDENT order by total desc;

select (select count(std_id) from STUDENT where mat > =25)*100/(select count(std_id) from STUDENT) as mat_pass_percentage from dual;

select (select count(std_id) from STUDENT where status='PASS')*100/(select count(std_id) from STUDENT) as overall_pass_percentage from dual;

select  avg(total) from STUDENT;

