CREATE TABLE CUSTOMER(
CustomerID  number generated by default as identity start with 1 increment by 1 primary key,
CustomerName varchar(20),
ContactNo varchar(20),
Address varchar(100),
City varchar(20),
PostalCode varchar(20),
Country varchar(60));


CREATE TABLE EMPLOYEES(
EmployeeID number generated by default as identity start with 1 increment by 1 primary key,
LastName varchar(100),
FirstName varchar(100),
BirthDate date);

CREATE TABLE ORDERS(
OrderID  number generated by default as identity start with 1 increment by 1 primary key,
CustomerID number,FOREIGN KEY(CustomerID) references CUSTOMER(CustomerID),
EmployeeID number ,FOREIGN KEY(EmployeeID) references EMPLOYEES(EmployeeID),
OrderDate date,
ShipperID number);


INSERT INTO CUSTOMER (CustomerName, ContactNo, Address, City,
PostalCode, Country) VALUES ('John Doe', '1234567890', '123 Elm
Street', 'New York', '10001', 'USA');

 INSERT INTO CUSTOMER (CustomerName, ContactNo, Address, City,
PostalCode, Country) VALUES ('Jane Smith', '2345678901', '456 Oak
Avenue', 'Los Angeles', '90001', 'USA');

INSERT INTO CUSTOMER (CustomerName, ContactNo, Address, City,
PostalCode, Country) VALUES ('Alice Johnson', '3456789012', '789 Pine
Road', 'Toronto', 'M5H2N2', 'Canada');

INSERT INTO CUSTOMER (CustomerName, ContactNo, Address, City,
PostalCode, Country) VALUES ('Bob Brown', '4567890123', '101 Maple
Drive', 'Mexico City', '01000', 'Mexico');

INSERT INTO CUSTOMER (CustomerName, ContactNo, Address, City,
PostalCode, Country) VALUES ('Eve White', '5678901234', '202 Cedar
Boulevard', 'London', 'EC11BB', 'UK');

INSERT INTO EMPLOYEES (LastName, FirstName, BirthDate)
VALUES ('Miller', 'Sarah', TO_DATE('1982-04-15', 'YYYY-MM-DD'));

INSERT INTO EMPLOYEES (LastName, FirstName, BirthDate)
VALUES ('Taylor', 'James', TO_DATE('1978-06-20', 'YYYY-MM-DD'));

INSERT INTO EMPLOYEES (LastName, FirstName, BirthDate)
VALUES ('Williams', 'Olivia', TO_DATE('1992-11-25', 'YYYY-MM-DD'));

INSERT INTO EMPLOYEES (LastName, FirstName, BirthDate)
VALUES ('Davis', 'Liam', TO_DATE('1985-01-09', 'YYYY-MM-DD'));

INSERT INTO EMPLOYEES (LastName, FirstName, BirthDate)
VALUES ('Martinez', 'Sophia', TO_DATE('1990-07-18', 'YYYY-MM-DD'));

INSERT INTO ORDERS (CustomerID, EmployeeID, OrderDate,
ShipperID) VALUES (1, 2, TO_DATE('2021-06-01', 'YYYY-MM-DD'), 1);

INSERT INTO ORDERS (CustomerID, EmployeeID, OrderDate,
ShipperID) VALUES (2, 3, TO_DATE('2020-12-15', 'YYYY-MM-DD'), 2);

INSERT INTO ORDERS (CustomerID, EmployeeID, OrderDate,
ShipperID) VALUES (3, 1, TO_DATE('2022-03-10', 'YYYY-MM-DD'), 3);

INSERT INTO ORDERS (CustomerID, EmployeeID, OrderDate,
ShipperID) VALUES (4, 4, TO_DATE('2021-07-22', 'YYYY-MM-DD'), 2);

INSERT INTO ORDERS (CustomerID, EmployeeID, OrderDate,
ShipperID) VALUES (5, 5, TO_DATE('2020-11-11', 'YYYY-MM-DD'), 1);




select * from Customer order by CustomerName ;
select * from ORDERS order by OrderDate;
select * from Employees where extract(year from BirthDate)>1980 order by birthdate desc;

select o.* from ORDERS o join customer c on o.Customerid = c.CustomerId where c.Country='USA' order by OrderDate DESC;

select c.CustomerName,count(o.OrderID) as TotalOrders from Customer C left join Orders o on c.CustomerID = o.OrderID group by c.CustomerName;

select count(CustomerID),city as TotalCustomers from Customer group by City;

select c.CustomerName,count(o.orderid) from customer c join orders o on c.customerid = o.customerid where count(o.orderid) >= 2 group by CustomerName;