CREATE TABLE ITEMS(itemid NUMBER GENERATED BY DEFAULT AS
IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
itemname varchar(50),
category varchar(50),
price number(6,2),
instock int,
CONSTRAINT stock_check CHECK (instock >= 0));
 
CREATE TABLE CUSTOMERS(custid NUMBER GENERATED BY
DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY
KEY,
custname varchar(100),
address varchar(70),
state varchar(50));

CREATE TABLE ORDERRS(orderid NUMBER GENERATED BY
DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY
KEY,
itemid int, FOREIGN KEY(itemid) REFERENCES ITEMS(itemid),
custid int, FOREIGN KEY(custid) REFERENCES CUSTOMERS(custid),
quantity int,
orderdate date);

CREATE TABLE DELIVERY(deliveryid NUMBER GENERATED BY
DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY
KEY,
custid int, FOREIGN KEY(custid) REFERENCES CUSTOMERS(custid),
orderid int, FOREIGN KEY(orderid) REFERENCES
ORDERRS(orderid));

drop table items;



INSERT INTO ITEMS (itemname, category, price, instock) VALUES
('Samsung GalaxyS4', 'Smartphone', 500.00, 20);
.
 INSERT INTO ITEMS (itemname, category, price, instock) VALUES
('Apple iPhone 13', 'Smartphone', 999.99, 15);

 INSERT INTO ITEMS (itemname, category, price, instock) VALUES
('Sony Headphones', 'Accessories', 150.00, 30);

 INSERT INTO ITEMS (itemname, category, price, instock) VALUES
('Dell Laptop', 'Electronics', 6000.00, 10);

INSERT INTO ITEMS (itemname, category, price, instock) VALUES
('Nikon Camera', 'Photography', 800.00, 25);

 INSERT INTO CUSTOMERS (custname, address, state) VALUES
('Mickey', '123 Main St, Springfield', 'Illinois');

INSERT INTO CUSTOMERS (custname, address, state) VALUES ('John
Doe', '456 Elm St, Chicago', 'Illinois');


INSERT INTO CUSTOMERS (custname, address, state) VALUES ('Sarah
Smith', '789 Oak St, Atlanta', 'Georgia');

 INSERT INTO CUSTOMERS (custname, address, state) VALUES
('James Brown', '101 Pine St, New York', 'New York');

INSERT INTO CUSTOMERS (custname, address, state) VALUES ('Emily
White', '202 Maple St, Los Angeles', 'California');

INSERT INTO ORDERRS (itemid, custid, quantity, orderdate) VALUES
(1, 1, 2, TO_DATE('01-03-2023', 'DD-MM-YYYY'));

 INSERT INTO ORDERRS (itemid, custid, quantity, orderdate) VALUES
(2, 2, 1, TO_DATE('15-06-2023', 'DD-MM-YYYY'));

 INSERT INTO ORDERRS (itemid, custid, quantity, orderdate) VALUES
(3, 3, 3, TO_DATE('22-01-2023', 'DD-MM-YYYY'));

INSERT INTO ORDERRS (itemid, custid, quantity, orderdate) VALUES
(4, 4, 1, TO_DATE('25-02-2023', 'DD-MM-YYYY'));

INSERT INTO ORDERRS (itemid, custid, quantity, orderdate) VALUES
(5, 5, 1, TO_DATE('11-07-2023', 'DD-MM-YYYY'));

INSERT INTO ORDERRS (itemid, custid, quantity, orderdate) VALUES
(2, 4, 1, TO_DATE('25-03-2023', 'DD-MM-YYYY'));

 INSERT INTO DELIVERY (custid, orderid) VALUES (1, 1);

INSERT INTO DELIVERY (custid, orderid) VALUES (2, 2);


INSERT INTO DELIVERY (custid, orderid) VALUES (3, 3);

 INSERT INTO DELIVERY (custid, orderid) VALUES (4, 2);
 
 select * from customers where custid in (select custid from orderrs);
 
 select * from customers where custid in ( select custid from delivery);
 
 select c.custname,o.orderdate from orderrs o join customers c on o.custid=c.custid where c.custname like 'J%';
 
 select itemname,price from items where itemid in ( select o.itemid from orderrs o join customers c on o.custid=c.custid where c.custname ='Mickey')

select * from customers  where custid in ( select custid from orderrs where orderdate> to_date('31-01-2013','DD-MM-YYYY') and custid not in (select custid from delivery));

select distinct itemid from orderrs union (select o.itemid from orderrs o where o.orderid not in ( select orderid from delivery));

(select c.custname from customers c join orderrs o on c.custid=o.custid) intersect (select c.custname from customers c join delivery d on c.custid = d.custid);

(select c.custname from customers c join orderrs o on o.custid=c.custid)minus(select c.custname from customers c join delivery d on c.custid = d.custid);

select c.custname,count(o.orderid) from customers c join orderrs o on o.custid = c.custid group by c.custname order by count(o.orderid) desc  fetch first 1 row only;

select  * from customers where custid in( select o.custid from orderrs o join items i on o.itemid=i.itemid where i.price>5000);

select * from customers where custid not in (select o.custid from orderrs o join items i on o.itemid=i.itemid where i.itemname='Samsung GalaxyS4'); 

select c.custid,c.custname,o.orderid,o.itemid from customers c right join orderrs o on o.custid=c.custid;

select custid,custname,state,count(*) from customers group by state ;

select itemid,itemname,category,price from items group by category,itemid,itemname,price having price>(select avg(price)from items);